---
title: "Homework 9"
author: "Dylan Snelsire"
---

Read in data for Problem 1

```{r}
cbb_scores<- read.csv('/Users/dylansnelsire/Downloads/2018_ncaab_scores.csv')
View(cbb_scores)
tournament_teams<- read.csv('/Users/dylansnelsire/Downloads/2018_tournament_teams.csv')
View(tournament_teams)

```

Problem 1a

```{r}
model = lm(margin ~ ., data = cbb_scores)
# Extract only coefficients from model summary
coefficients = coef(model, complete=TRUE)

# Change baseline team's rating from NA to 0
coefficients[length(coefficients)] = 0   

# Calculate the amount ratings need to be adjusted by, equal to the sum of the coefficients for the teams that are not the baseline divided by the number of teams in the league
adj = -1*sum(coefficients[2:length(coefficients)])/(length(coefficients)-1)
head(coefficients, 10)
 sigma(model)


```

Problem 1b

```{r}
# Adjust the ratings by adding the adjustment to each team's rating, leaving the intercept alone.  The sum of the coefficients should now be equal to the intercept, meaning the average rating for all teams is 0.
ratings = c(coefficients[1], coefficients[2:length(coefficients)] + adj)  
head(ratings, 10)
```

Problem 1c

```{r}
set.seed(31)  # Random seed to replicate results
iterations = 10000  # Number of tournaments to simulate
teams = 64  # Number of teams in tournament, rounded up to the nearest power of 2
league_sd = sigma(model)  # Residual standard deviation of Bradley-Terry model

# Matrix to hold winners of each game in each tournament.  Each row is a different simulation and each column is a different game.  For example, column 1 will always hold the winner of the Gonzaga-Norfolk St. game while column 63 will always hold the winner of the championship game.
results = matrix(0, iterations, teams-1)  

# Initialize data frame to hold teams, ratings, and final simulation results.
tournament_ratings = data.frame(matrix(ncol = 10, nrow = teams))
colnames(tournament_ratings) = c("team", "seed", "region", "rating", "R32", "SS", "EE", "FF", "CG", "Champ")

tournament_ratings$team = tournament_teams$team
tournament_ratings$seed = tournament_teams$seed
tournament_ratings$region = tournament_teams$region

# Populate first two columns with team names and ratings
for(i in 1:teams) {
  tournament_ratings$rating[i] = as.numeric(ratings[tournament_teams$team[i]])
}

# Begin simulation
for(i in 1:iterations) {
  current_round = tournament_teams$team    # List of all teams currently in the tournament
  next_round = NULL    # List that will contain the winners of each round
  winners = NULL       # List that will contain the winners of all 63 games
  
  while(length(current_round) > 1) {  # Continue simulating while at least 2 teams remain
    for(j in 1:(length(current_round)/2)) {  # Number of games equals half number of teams
      team_1 = current_round[2*j-1]  # Home team is in the 2*j-1 location of teams remaining
      team_2 = current_round[2*j]    # away team is in the 2*j location of teams remaining
    
      # Obtain rating for teams in current game
      r1 = ratings[team_1]
      r2 = ratings[team_2]
      
      win_prob = 1 - pnorm((0-(r1-r2))/league_sd, 0, 1)  # Calculate win prob for team_1
      u = runif(1, 0, 1)
  
      # Determine winner of current game
      if(u < win_prob) {
        next_round = c(next_round, team_1)
      } else {
        next_round = c(next_round, team_2)
      }
    }
    
    # After all games in current round have been simulated
    current_round = next_round    # Set the teams remaining equal to the teams that won
    winners = c(winners, next_round)  # Add the winning teams to the 'winners' list
    next_round = NULL    # Reset the list of teams that won in the current round to be empty
  }
  results[i,] = winners  # Set the row i in the 'results' matrix equal to the list of winners
}

# Calculate the proportion of times each team advanced to each round
for(i in 1:teams) {  # For each team in the tournament
  tournament_ratings$R32[i] = length(which(results[,1:32] == tournament_teams$team[i]))/iterations
  tournament_ratings$SS[i] = length(which(results[,33:48] == tournament_teams$team[i]))/iterations
  tournament_ratings$EE[i] = length(which(results[,49:56] == tournament_teams$team[i]))/iterations
  tournament_ratings$FF[i] = length(which(results[,57:60] == tournament_teams$team[i]))/iterations
  tournament_ratings$CG[i] = length(which(results[,61:62] == tournament_teams$team[i]))/iterations
  tournament_ratings$Champ[i] = length(which(results[,63] == tournament_teams$team[i]))/iterations
}
tournament_ratings
tournament_teams
```

Problem 1g

```{r}
resultsf <-results[,c(61:62)]
#resultsf
names(results)
#(resultsf1 <- results[with(results, 61 == "michigan" & 61 == "villanova"), ])
```

Read in data for Problem 2

```{r}
scores<- read.csv('/Users/dylansnelsire/Downloads/nba_scores.csv')
View(scores)
team_info<- read.csv('/Users/dylansnelsire/Downloads/nba_initial_elos (1).csv')
View(team_info)
```

Problem 2a

```{r}
pre_season <-scores[ which(scores$season < 2015), ]
pre_season
season_schedule <-scores[ which(scores$game_type=='r'), ]
season_schedule

```

Problem 2b

```{r, echo=FALSE}

weight = 8.7
hfa = 78.79

# Iterate through all games in the sport's history up to season being simulated
for(i in 1:nrow(pre_season)) {
  # Find indices corresponding to home and away teams for current game
  home_index = which(team_info$team == pre_season$home_team[i])
  away_index = which(team_info$team == pre_season$away_team[i])
  
  # Find home and away team Elo ratings
  home_elo = team_info$rating[home_index]
  away_elo = team_info$rating[away_index]

  # Calculate home team win probability
  win_prob = 1 / (10^((away_elo - (home_elo + hfa*pre_season$neutral[i]))/400) + 1)

  # Calculate actual margin of victory - must be positive
  score_diff = abs(pre_season$home_score[i] - pre_season$away_score[i])   
  
  # Determine home team result
  if(pre_season$home_score[i] > pre_season$away_score[i]) { 
    home_result = 1  # Home team wins
  } else if(pre_season$home_score[i] < pre_season$away_score[i]) { 
    home_result = 0  # Home team loses
  } else { 
    home_result = 0.5  # Tie
  }
  
  # Calculate amount each team's Elo rating is adjusted by
  home_elo_adjustment = weight * log(score_diff + 1) * (home_result - win_prob)
  
  # Adjust Elo ratings - add point to winner and subtract points from loser
  team_info$rating[home_index] = team_info$rating[home_index] + home_elo_adjustment
  team_info$rating[away_index] = team_info$rating[away_index] - home_elo_adjustment
  
  # Adjust Elo ratings at end of season to regress 1/3 of the way towards 1500
  if(i < nrow(scores) && scores$season[i+1] > scores$season[i]) {
    for(j in 1:nrow(team_info)) {
      if(scores$season[i] >= team_info$inaugural_season[j]) {
        team_info$rating[j] = team_info$rating[j] - (team_info$rating[j] - 1500)/3
      }
    }
    
    # Identify all teams that existed at beginning of following season
    existing_teams = team_info[which(team_info$inaugural_season <= (scores$season[i] + 1)),]
    
    # Calculate amount each team's Elo rating must be adjusted by to make mean 1500
    expansion_adjustment = -1*(mean(existing_teams$rating) - 1500)
    
    # Perform expansion adjustment on teams that existed at beginning of following season
    for(j in 1:nrow(team_info)) {
      if((scores$season[i] + 1) >= team_info$inaugural_season[j]) {
        team_info$rating[j] = team_info$rating[j] + expansion_adjustment
      }
    }
  }
}
print(team_info)
```

Problem 2c

```{r, echo=FALSE}
# Set seed for replication purposes
set.seed(37)

# Determine number of times to simulate the season
iterations = 10

# Create data frame to hold actual win totals and simulation results
results = data.frame(matrix(0, ncol = 3, nrow = nrow(team_info)))
colnames(results) = c("team", "actual_wins", "average_wins")
results$team = team_info$team

# Create data frame to hold number of wins by each team in each iteration
win_totals = data.frame(matrix(0, ncol = nrow(team_info), nrow = iterations))
colnames(win_totals) = team_info$team

# Simulate the season the given number of times
for(i in 1:iterations) {
  if(i %% 1000 == 0) {print(i)}
  season_stats = team_info[,which(colnames(team_info) != "inaugural_season")]
  season_stats$wins = 0
  season_stats$rand = runif(nrow(team_info))
  
  # Simulate each game in current season
  for(j in 1:nrow(season_schedule)) {
    # Find indices corresponding to home and away teams for current game
    home_index = which(season_stats$team == season_schedule$home_team[j])
    away_index = which(season_stats$team == season_schedule$away_team[j])
  
    # Find home and away team Elo ratings
    home_elo = season_stats$rating[home_index]
    away_elo = season_stats$rating[away_index]

    # Calculate home team win probability
    win_prob = 1 / (10^((away_elo - (home_elo + hfa*season_schedule$neutral[j]))/400) + 1)
    u = runif(1)  # Generate a random number used to determine the winner of the game
    
    # Determine which team wins the simulated game and increment their win total by 1
    if(u < win_prob) {
      season_stats$wins[home_index] = season_stats$wins[home_index] + 1
    } else {
      season_stats$wins[away_index] = season_stats$wins[away_index] + 1
    }
    
    # Calculate actual margin of victory - must be positive
    score_diff = abs(season_schedule$home_score[j] - season_schedule$away_score[j])
  
    # Determine home team result
    if(season_schedule$home_score[j] > season_schedule$away_score[j]) { 
      home_result = 1  # Home team wins
    } else if(season_schedule$home_score[j] < season_schedule$away_score[j]) { 
      home_result = 0  # Home team loses
    } else { 
      home_result = 0.5  # Tie
    }
    
    # Calculate amount each team's Elo rating is adjusted by
    home_elo_adjustment = weight * log(score_diff + 1) * (home_result - win_prob)
  
    # Adjust Elo ratings after game has been simulated to get team's new strength
    season_stats$rating[home_index] = season_stats$rating[home_index] + home_elo_adjustment
    season_stats$rating[away_index] = season_stats$rating[away_index] - home_elo_adjustment
    
    # Track season wins
    if(i == 1) {
      if(season_schedule$home_score[j] > season_schedule$away_score[j]) {
        results$actual_wins[home_index] = results$actual_wins[home_index] + 1
      } else if(season_schedule$home_score[j] < season_schedule$away_score[j]) {
        results$actual_wins[away_index] = results$actual_wins[away_index] + 1
      } else {
        results$actual_wins[home_index] = results$actual_wins[home_index] + 0.5
        results$actual_wins[away_index] = results$actual_wins[away_index] + 0.5
      }
    }
  }


  

  
  # Save end of season win totals (from column 5 of season_stats) for each iteration in the win_totals data frame
  win_totals[i,] = t(season_stats[5])
    
  # Add number of wins for each team during this iteration to sum
  results$average_wins = results$average_wins + season_stats$wins
  
 
  }

 
# Calculate average number of wins across all iterations
results$average_wins = results$average_wins/iterations
print(results)

```

Problem 2d

```{r}
results

resid <- results$actual_wins - results$average_wins
resid

hist(resid)
plot(resid,results$actual_wins)
plot(results$average_wins, results$actual_wins)
```
